type Photo @embedded {
  url: String!
  caption: String!
}

type WordMeaning @embedded {
  definition: String!
  english: [String]
  examples: [String]!
  photos: [Photo]
}

type Word {
  partOfSpeech: String!
  german: String! @unique
  definitions: [WordMeaning]!
}

type LearningLog {
  tick: Int!
  word: String!
  definitionIndex: Int!
  questionType: String!
  miss: Boolean!
}

type Query {
  words: [Word]!
  learningLogs: [LearningLog]!
}
