type Photo @embedded {
  url: String!
  caption: String!
}

type WordMeaning @embedded {
  definition: String!
  english: [String]
  examples: [String]!
  photos: [Photo]
  synonyms: [String]!
  antonyms: [String]!
  genericTerms: [String]!
  subTerms: [String]!
}

type Word {
  partOfSpeech: String!
  german: String! @unique
  definitions: [WordMeaning]!
}

type LearningLog {
  sessionId: String!
  word: String!
  definitionIndex: Int!
  questionType: String!
  miss: Boolean!
}

type Query {
  words: [Word]!
  learningLogs(sessionId: String!): [LearningLog]!
}
